### ISSUE TITLE
Bug: Could not open requirements file

### ISSUE THREAD

**Issue by hammadarshad1** [py-actions/py-dependency-install#87]
I have the `requirements.txt` file in my project root directory but the action fails and says `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`. I've also attached an attachment that shows my requirements.txt file location.

**Comment by chrissimpkins** [comment]
Sorry for the troubles!  Can you paste your py-dependency-install action configuration into this thread so that I can have a look?

**Comment by hammadarshad1** [comment]
> Sorry for the troubles! Can you paste your py-dependency-install action configuration into this thread so that I can have a look?

Yes here it is:

```
name: Dependency check

on: [push]

jobs:
  dependencies_check:
    runs-on: ubuntu-latest
    steps:
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
```

**Comment by chrissimpkins** [comment]
Ty

Does it happen to work if you add an explicit path definition as shown in https://github.com/py-actions/py-dependency-install#define-the-requirementstxt-path?

**Comment by hammadarshad1** [comment]
> Ty
> 
> Does it happen to work if you add an explicit path definition as shown in https://github.com/py-actions/py-dependency-install#define-the-requirementstxt-path?

I didn't add an explicit path of the file because by default this action is looking for the `requirements.txt` on the project root directory. Here is the reference https://github.com/py-actions/py-dependency-install#path

**Comment by chrissimpkins** [comment]
I understand.  You are correct.  That is how I designed it.  Can you try adding the explicit path to your configuration to see if it works with that approach? I am trying to understand if this is related to how the default path handling is managed by the action source and don't have the ability to test against this default path definition in our CI tests.

**Comment by hammadarshad1** [comment]
Okay @chrissimpkins, let me check with the explicit path.

**Comment by hammadarshad1** [comment]
Still pointing out the same bug. I also attached a screenshot for your reference.
![image](https://user-images.githubusercontent.com/45298916/133618917-29529b0a-0991-4adc-9831-f909affceb8b.png)

**Comment by chrissimpkins** [comment]
Very strange.  The pip install command looks ok.  Does the following command work locally from the root of your repo in a virtual environment?

```
pip install -r requirements.txt
```

**Comment by hammadarshad1** [comment]
Yes, I've set up other actions and also used `pip install -r requirements.txt`, and it's working fine there. Here I wanted to use new things on an experimental basis so, I come up with your repo after searching for few minutes.

**Comment by chrissimpkins** [comment]
Sorry that this didn't work for you.  I have it running in projects with explicit path definitions to the requirements file.  I'll need to set up a new repo to see if I can reproduce your issue.  Not sure what is going on.

**Comment by hammadarshad1** [comment]
> Sorry that this didn't work for you. I have it running in projects with explicit path definitions to the requirements file. I'll need to set up a new repo to see if I can reproduce your issue. Not sure what is going on.

Thank you very much @chrissimpkins, I am also figuring it out on my side as well if I can come with a solution.

**Comment by antonio-hickey** [comment]
Having this same problem, my requirements.txt is placed at the root of my repo but i've tried both explicitly defining the path and not both are not able to find it.

**Comment by chrissimpkins** [comment]
I'll definitely dive into this when some time opens up.  I'm not sure what is going on.  Our CI nightly builds with explicit file requirements paths defined continue to pass.  Are any of your repositories open so that I can have a look at the file structure and GHA config file?

**Comment by antonio-hickey** [comment]
> I'll definitely dive into this when some time opens up. I'm not sure what is going on. Our [nightly CI builds with explicit requirements file paths defined](https://github.com/py-actions/py-dependency-install/actions) continue to pass. Are any of your repositories open so that I can have a look at the file structure and GHA config file?

Yea the repo I was trying it with is https://github.com/antonio-hickey/dReserve although I'm currently not using it bc I had to find a fix around the error so i'm just importing depends manually.

**Comment by chrissimpkins** [comment]
I forked your dReserve repo and the default py-dependency-install approach appears to work for me.

https://github.com/chrissimpkins/dReserve/pull/1

Are you installing the cPython environment with https://github.com/actions/setup-python before you attempt to execute the Python dependency installations with py-dependency-install?  This is how my configuration looks:

```yaml

  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Run py-dependency-install test
        uses: py-actions/py-dependency-install@master
```

If you need multiple cPy version CI testing, it is possible to define a matrix like we do in this project's unit tests: https://github.com/py-actions/py-dependency-install/blob/7ca98418a32ec5ee898ec3df01d5701ce1516a43/.github/workflows/linuxci.yml#L11-L22

Let me know if this happens to solve the issue for you.  I can make this clear in the docs.
